FROM node:20

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar package.json y package-lock.json para instalar dependencias primero
COPY package*.json ./

# Instalar las dependencias
RUN npm install --omit=dev

# Copiar el resto de la aplicación
COPY . .

# Exponer el puerto en el que corre tu aplicación
EXPOSE 3900

# Comando para ejecutar la aplicación
CMD ["node", "index.js"]
