# fly.toml app configuration file generated for api-res-7a-full on 2025-04-05T12:20:47-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'api-res-7a-full'
primary_region = 'gdl'

[build]

[http_service]
  internal_port = 3900
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
